import json
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, ALERT_EMAIL, MOCK_EMAIL


def _build_html_body(state: dict, report: dict) -> str:
    alert = state["alert"]
    decision = state.get("decision", "unknown")
    reasoning = state.get("reasoning_summary", "Not available.")

    try:
        action_data = json.loads(state.get("action_taken", "{}"))
    except Exception:
        action_data = {}

    is_resolved = decision == "auto_resolve"
    status_color = "#27ae60" if is_resolved else "#e74c3c"
    status_icon = "✅" if is_resolved else "🚨"
    status_label = "AUTO-RESOLVED" if is_resolved else "REQUIRES HUMAN ATTENTION"

    next_steps_html = "".join(
        f"<li style='margin-bottom:6px;'>{step}</li>"
        for step in report.get("next_steps", [])
    )

    return f"""<!DOCTYPE html>
<html>
<body style="font-family:Arial,sans-serif;max-width:780px;margin:0 auto;background:#f4f4f4;padding:20px;">

  <div style="background:{status_color};color:white;padding:24px 28px;border-radius:8px 8px 0 0;">
    <h1 style="margin:0;font-size:22px;">{status_icon} Incident {status_label}</h1>
    <p style="margin:8px 0 0;font-size:16px;">
      Service: <strong>{alert.get('service')}</strong> &nbsp;|&nbsp;
      Severity: <strong>{(alert.get('severity') or '').upper()}</strong>
    </p>
  </div>

  <div style="background:white;padding:24px 28px;border:1px solid #ddd;border-top:none;">

    <h3 style="color:#2c3e50;margin-top:0;">📋 Alert Details</h3>
    <table style="width:100%;border-collapse:collapse;font-size:14px;">
      <tr style="background:#f8f9fa;">
        <td style="padding:8px 12px;font-weight:bold;width:160px;">Alert ID</td>
        <td style="padding:8px 12px;">{alert.get('alert_id')}</td>
      </tr>
      <tr>
        <td style="padding:8px 12px;font-weight:bold;">Service</td>
        <td style="padding:8px 12px;">{alert.get('service')}</td>
      </tr>
      <tr style="background:#f8f9fa;">
        <td style="padding:8px 12px;font-weight:bold;">Description</td>
        <td style="padding:8px 12px;">{alert.get('description')}</td>
      </tr>
      <tr>
        <td style="padding:8px 12px;font-weight:bold;">Triggered At</td>
        <td style="padding:8px 12px;">{alert.get('timestamp')}</td>
      </tr>
      <tr style="background:#f8f9fa;">
        <td style="padding:8px 12px;font-weight:bold;">Incident ID</td>
        <td style="padding:8px 12px;">{report.get('incident_id')}</td>
      </tr>
    </table>

    <h3 style="color:#2c3e50;">🔍 Root Cause Analysis</h3>
    <div style="background:#f8f9fa;padding:16px;border-left:4px solid #3498db;
                border-radius:4px;font-size:13px;white-space:pre-wrap;font-family:monospace;">
{reasoning}
    </div>

    <h3 style="color:#2c3e50;">⚡ Action Taken</h3>
    <div style="background:#f8f9fa;padding:16px;
                border-left:4px solid {status_color};border-radius:4px;">
      <pre style="margin:0;font-size:13px;white-space:pre-wrap;">{json.dumps(action_data, indent=2)}</pre>
    </div>

    <h3 style="color:#2c3e50;">📌 Next Steps</h3>
    <ul style="font-size:14px;line-height:1.6;">
      {next_steps_html}
    </ul>

    <hr style="border:none;border-top:1px solid #eee;margin:24px 0;">
    <p style="color:#95a5a6;font-size:11px;margin:0;">
      Generated by <strong>Autonomous Incident Commander</strong> &nbsp;|&nbsp;
      Bayer AI Hackathon 2026 — Agentic AI Track<br>
      Report generated: {report.get('generated_at')}
    </p>
  </div>

</body>
</html>"""


def send_incident_email(state: dict, report: dict) -> bool:
    """
    Send an incident notification email.
    When MOCK_EMAIL=true (default), logs the email to stdout instead of sending.
    Returns True on success, False on failure.
    """
    alert = state["alert"]
    decision = state.get("decision", "unknown")
    status = "RESOLVED" if decision == "auto_resolve" else "ACTION REQUIRED"
    subject = (
        f"[{status}] Incident: {alert.get('service')} — "
        f"{(alert.get('severity') or '').upper()} | {report.get('incident_id')}"
    )

    html_body = _build_html_body(state, report)

    if MOCK_EMAIL:
        print("\n" + "=" * 70)
        print(f"[MOCK EMAIL]  To      : {ALERT_EMAIL}")
        print(f"[MOCK EMAIL]  Subject : {subject}")
        print(f"[MOCK EMAIL]  Decision: {decision}")
        print(f"[MOCK EMAIL]  Body    : {len(html_body)} chars (HTML)")
        print("=" * 70 + "\n")
        return True

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = SMTP_USER
        msg["To"] = ALERT_EMAIL
        msg.attach(MIMEText(html_body, "html"))

        ctx = ssl.create_default_context()
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls(context=ctx)
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(SMTP_USER, ALERT_EMAIL, msg.as_string())

        print(f"[Email] Notification sent to {ALERT_EMAIL}")
        return True
    except Exception as exc:
        print(f"[Email] Failed to send: {exc}")
        return False
